# -*- coding: utf-8 -*-
"""
=============================================================================
demo_pipeline.py -- Offline Demo (No Database Required)
=============================================================================
Runs the FULL transformation pipeline using only CSV/Excel files.
Useful for testing locally or demonstrating the project without
configuring real database connections.

What it does:
  1. Reads mock_orders.csv, mock_products.csv, sample_customers.xlsx
     (generated by generate_sample_data.py)
  2. Runs the full transform phase (all cleaning, merging, derived cols)
  3. Saves the output to data/pipeline_output.csv
  4. Prints a summary report to the console

Run:
    python demo_pipeline.py
=============================================================================
"""

import pandas as pd
import time
from utils.logger import get_logger
from transform import run_transformation

logger = get_logger(__name__, log_file="logs/demo.log")


def run_demo():
    start = time.perf_counter()

    logger.info("=" * 60)
    logger.info("DEMO PIPELINE -- Offline Mode (CSV + Excel, no DB)")
    logger.info("=" * 60)

    # -- Load raw files -------------------------------------------------------
    logger.info("Reading source files...")
    try:
        orders    = pd.read_csv("data/mock_orders.csv")
        products  = pd.read_csv("data/mock_products.csv")
        customers = pd.read_excel(
            "data/sample_customers.xlsx",
            sheet_name="Customers",
            engine="openpyxl",
        )
    except FileNotFoundError as e:
        logger.error(
            "File not found: %s\n"
            "Run 'python generate_sample_data.py' first to create the sample files.",
            e,
        )
        return

    logger.info("  orders    -> %d rows x %d cols", *orders.shape)
    logger.info("  products  -> %d rows x %d cols", *products.shape)
    logger.info("  customers -> %d rows x %d cols", *customers.shape)

    datasets = {
        "orders":    orders,
        "products":  products,
        "customers": customers,
    }

    # -- Run transformation ---------------------------------------------------
    master_df = run_transformation(datasets)

    # -- Save output ----------------------------------------------------------
    output_path = "data/pipeline_output.csv"
    master_df.to_csv(output_path, index=False)
    logger.info("Output saved -> %s", output_path)

    # -- Summary Report -------------------------------------------------------
    elapsed = time.perf_counter() - start

    print("\n" + "=" * 57)
    print("  PIPELINE SUMMARY REPORT")
    print("=" * 57)
    print(f"  Total rows processed  : {len(master_df):,}")
    print(f"  Total columns         : {len(master_df.columns)}")
    print(f"  Elapsed time          : {elapsed:.2f}s")
    print(f"  Output file           : {output_path}")
    print("=" * 57)

    print("\n  Column Overview:")
    print(f"  {'Column':<28} {'DType':<14} {'Null%':>6}")
    print("  " + "-" * 52)
    for col in master_df.columns:
        dtype    = str(master_df[col].dtype)
        null_pct = master_df[col].isnull().mean() * 100
        print(f"  {col:<28} {dtype:<14} {null_pct:5.1f}%")

    if "revenue" in master_df.columns:
        print("\n  Revenue Stats:")
        print(f"    Total Revenue     : ${master_df['revenue'].sum():>13,.2f}")
        print(f"    Mean Revenue      : ${master_df['revenue'].mean():>13,.2f}")
        print(f"    Max Revenue       : ${master_df['revenue'].max():>13,.2f}")
        if "is_high_value" in master_df.columns:
            high_val_pct = master_df["is_high_value"].mean() * 100
            print(f"    High-Value Orders : {high_val_pct:.1f}%")
        if "net_revenue" in master_df.columns:
            print(f"    Total Net Revenue : ${master_df['net_revenue'].sum():>13,.2f}")

    print("\n" + "=" * 57)
    print("\n  First 5 rows of output:")
    print(master_df.head(5).to_string())
    print("=" * 57 + "\n")


if __name__ == "__main__":
    run_demo()
